from __future__ import annotations

import re
from pathlib import Path

from .cubemx import (
    enabled_instances,
    gpio_ports,
    init_functions,
    openocd_target_for_family,
    startup_define,
)


def cmake_list(values) -> str:
    values = list(values)
    if not values:
        return ""
    return "\n".join(f"        {value}" for value in values)


def write_if_missing(path: Path, content: str) -> None:
    if path.exists():
        return
    path.write_text(content, encoding="utf-8")


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def discover_cubemx_init_functions(board_dir: Path) -> list[tuple[str, str, str]]:
    discovered: list[tuple[str, str, str]] = []
    for header in sorted((board_dir / "Core/Inc").glob("*.h")):
        text = header.read_text(encoding="utf-8", errors="ignore")
        for match in re.finditer(r"^\s*void\s+(MX_([A-Za-z0-9]+).*_Init)\s*\(\s*void\s*\)\s*;", text, re.MULTILINE):
            function = match.group(1)
            ip = match.group(2)
            discovered.append((function, ip, header.name))
    return discovered


def write_board_config(board_dir: Path, values: dict[str, str]) -> Path:
    generated_dir = board_dir / "generated"
    generated_dir.mkdir(exist_ok=True)

    uart_instances = enabled_instances(values, "USART") + enabled_instances(values, "UART")
    spi_instances = enabled_instances(values, "SPI")
    timer_instances = enabled_instances(values, "TIM")
    ports = gpio_ports(values)

    timer_count = max(timer_instances) if timer_instances else 1

    uart_defines = "\n".join(
        f"#define BOARD_UART{index:<2}        {1 if index in uart_instances else 0}"
        for index in range(1, 4)
    )
    spi_defines = "\n".join(
        f"#define BOARD_SPI{index:<2}         {1 if index in spi_instances else 0}"
        for index in range(1, 4)
    )
    timer_defines = "\n".join(
        f"#define BOARD_TIM{index:<2}         {1 if index in timer_instances else 0}"
        for index in range(1, 18)
    )
    port_defines = "\n".join(
        f"#define BOARD_HAS_GPIO{port[-1]}     1"
        for port in ports
    )

    content = f"""/* Generated by tools/board_sync; do not edit by hand. */
#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#define BOARD_UART_COUNT    {len(uart_instances)}
#define BOARD_SPI_COUNT     {len(spi_instances)}
#define BOARD_TIMER_COUNT   {timer_count}
#define BOARD_DMA           {1 if "DMA" in values.values() else 0}

{uart_defines}

{spi_defines}

{timer_defines}

{port_defines}

#endif /* BOARD_CONFIG_H */
"""
    path = generated_dir / "board_config.h"
    write_if_changed(path, content)
    return path


def write_board_glue(board_dir: Path, values: dict[str, str]) -> Path:
    generated_dir = board_dir / "generated"
    generated_dir.mkdir(exist_ok=True)

    def header_for_ip(ip: str) -> str:
        if ip.startswith("USART") or ip.startswith("UART"):
            return "usart.h"
        if ip.startswith("SPI"):
            return "spi.h"
        if ip.startswith("TIM"):
            return "tim.h"
        return f"{ip.lower()}.h"

    init_entries = [(function, ip, header_for_ip(ip)) for function, ip in init_functions(values)]
    known_functions = {function for function, _, _ in init_entries}
    for function, ip, header in discover_cubemx_init_functions(board_dir):
        if function not in known_functions:
            init_entries.append((function, ip, header))
            known_functions.add(function)

    includes = ["main.h"]
    for _, _, header in init_entries:
        if (board_dir / "Core/Inc" / header).exists() and header not in includes:
            includes.append(header)

    include_lines = "\n".join(f'#include "{header}"' for header in includes)
    init_calls = "\n".join(
        f"    {function}();"
        for function, _, _ in init_entries
        if function != "SystemClock_Config"
    )

    if not init_calls:
        init_calls = "    /* No CubeMX peripheral init functions were listed in the .ioc file. */"

    content = f"""/* Generated by tools/board_sync; do not edit by hand. */
{include_lines}

void SystemClock_Config(void);

#if defined(__GNUC__)
#define HSS_WEAK __attribute__((weak))
#else
#define HSS_WEAK
#endif

HSS_WEAK void clock_init(void)
{{
    SystemClock_Config();
}}

HSS_WEAK void board_clock_config(void)
{{
    clock_init();
}}

HSS_WEAK void board_init(void)
{{
{init_calls}
}}
"""
    path = generated_dir / "board_glue.c"
    write_if_changed(path, content)
    return path


def write_manifest(
    board_dir: Path,
    values: dict[str, str],
    ioc: Path,
    startup: Path,
    linker: Path,
    hal_driver_dir: Path,
    device_dir: Path,
    cpu: str,
    cpu_flags: list[str],
    core_sources: list[str],
    ips: list[str],
    board_glue: Path,
) -> Path:
    project_name = values.get("ProjectManager.ProjectName", board_dir.name)
    family = values["Mcu.Family"].lower()

    content = f"""# Generated by tools/board_sync; do not edit by hand.
# Source: {ioc.name}

set(BOARD_NAME {project_name})
set(BOARD_CUBEMX_IOC ${{CMAKE_CURRENT_LIST_DIR}}/{ioc.name})
set(BOARD_MCU_FAMILY {family})
set(BOARD_MCU_DEVICE {values.get("ProjectManager.DeviceId", values.get("Mcu.UserName", ""))})
set(BOARD_MCU_DEFINE {startup_define(startup)})
set(BOARD_CPU {cpu})

set(BOARD_CPU_FLAGS
{cmake_list(cpu_flags)}
)

set(BOARD_OPENOCD_INTERFACE interface/stlink.cfg)
set(BOARD_OPENOCD_TARGET {openocd_target_for_family(family)})
set(BOARD_OPENOCD_TRANSPORT hla_swd)

set(BOARD_LINKER_SCRIPT ${{CMAKE_CURRENT_LIST_DIR}}/{linker.relative_to(board_dir).as_posix()})
set(BOARD_STARTUP_SOURCE ${{CMAKE_CURRENT_LIST_DIR}}/{startup.relative_to(board_dir).as_posix()})
set(BOARD_GENERATED_DIR ${{CMAKE_CURRENT_LIST_DIR}}/generated)
set(BOARD_GENERATED_INCLUDE_DIR ${{BOARD_GENERATED_DIR}})

set(BOARD_CORE_INCLUDE_DIR ${{CMAKE_CURRENT_LIST_DIR}}/Core/Inc)
set(BOARD_CORE_SOURCES
{cmake_list("${CMAKE_CURRENT_LIST_DIR}/" + source for source in core_sources)}
)
set(BOARD_GLUE_SOURCES
        ${{CMAKE_CURRENT_LIST_DIR}}/{board_glue.relative_to(board_dir).as_posix()}
)

set(BOARD_HAL_DRIVER_DIR ${{CMAKE_CURRENT_LIST_DIR}}/{hal_driver_dir.relative_to(board_dir).as_posix()})
set(BOARD_CMSIS_CORE_DIR ${{CMAKE_CURRENT_LIST_DIR}}/Drivers/CMSIS/Include)
set(BOARD_CMSIS_DEVICE_DIR ${{CMAKE_CURRENT_LIST_DIR}}/{device_dir.relative_to(board_dir).as_posix()}/Include)

set(BOARD_CUBEMX_IPS
{cmake_list(ips)}
)
"""
    path = board_dir / "board_manifest.cmake"
    write_if_changed(path, content)
    return path


def write_roles(board_dir: Path, values: dict[str, str]) -> Path:
    project_name = values.get("ProjectManager.ProjectName", board_dir.name)
    content = f"""# Framework-owned semantic role mapping for {project_name}.
# This file is created once by tools/board_sync and is safe to edit.
# Rerunning the sync script will not overwrite it.

# Examples:
# set(BOARD_ROLE_CONSOLE_UART USART1)
# set(BOARD_ROLE_DEBUG_UART USART2)
# set(BOARD_ROLE_MODBUS_UART USART1)
# set(BOARD_ROLE_MODBUS_TIMER TIM2)
# set(BOARD_ROLE_MODBUS_RS485_MODE manual)
# set(BOARD_ROLE_MODBUS_RS485_DE PA8)
# set(BOARD_ROLE_MODBUS_RS485_DE_ACTIVE_HIGH ON)
# set(BOARD_ROLE_SENSOR_SPI SPI1)
# set(BOARD_ROLE_SENSOR_CS PA4)
# set(BOARD_ROLE_SENSOR_CS_ACTIVE_LOW ON)
# set(BOARD_ROLE_STATUS_LED PC13)
# set(BOARD_ROLE_STATUS_LED_ACTIVE_LOW ON)
"""
    path = board_dir / "board_roles.cmake"
    write_if_missing(path, content)
    return path
