from __future__ import annotations

import json
from pathlib import Path

from .model import ConfigValue


def c_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def c_literal(config_value: ConfigValue) -> str:
    if config_value.kind == "bool":
        return "1" if bool(config_value.value) else "0"
    if config_value.kind == "int":
        return str(config_value.value)
    return f'"{c_escape(str(config_value.value))}"'


def macro_name(key: str) -> str:
    if key.startswith("HSS_") or key.startswith("CONFIG_"):
        return key
    return f"CONFIG_{key}"


def is_c_facing(key: str) -> bool:
    return key.startswith("HSS_") or key.startswith("APP_") or key.startswith("CONFIG_")


def cmake_definition(config_value: ConfigValue) -> str:
    name = macro_name(config_value.key)
    if config_value.kind == "string":
        return f'{name}=\\"{c_escape(str(config_value.value))}\\"'
    return f"{name}={c_literal(config_value)}"


def generated_header(values: dict[str, ConfigValue], profiles: list[str]) -> str:
    lines = [
        "/* Generated by HSS STM32 framework; do not edit by hand. */",
        "#pragma once",
        "",
        f'#define HSS_CONFIG_ACTIVE_PROFILES "{c_escape(";".join(profiles))}"',
    ]
    for profile in profiles:
        lines.append(f"#define HSS_CONFIG_PROFILE_{profile.upper()} 1")
    if profiles:
        lines.append("")
    for key in sorted(values):
        if not is_c_facing(key):
            continue
        lines.append(f"#define {macro_name(key)} {c_literal(values[key])}")
    lines.append("")
    return "\n".join(lines)


def generated_cmake(values: dict[str, ConfigValue], profiles: list[str], loaded_files: list[Path]) -> str:
    all_definitions = ";".join(
        cmake_definition(values[key])
        for key in sorted(values)
        if is_c_facing(key)
    )
    framework_definitions = ";".join(
        cmake_definition(values[key])
        for key in sorted(values)
        if key in {
            "HSS_ENABLE_MODBUS_DEBUG",
            "HSS_ENABLE_EEPROM_EMULATION",
            "HSS_ENABLE_WATCHDOG",
            "HSS_CONSOLE_STDIO_TIMEOUT_MS",
            "HSS_EEPROM_FLASH_ORIGIN",
            "HSS_EEPROM_FLASH_SIZE",
            "HSS_EEPROM_PAGE_SIZE",
            "HSS_EEPROM_SLOT_COUNT",
        }
    )
    lines = [
        "# Generated by HSS STM32 framework; do not edit by hand.",
        f'set(HSS_CONFIG_ACTIVE_PROFILES "{(";".join(profiles))}")',
        "set(HSS_CONFIG_LOADED_FILES",
    ]
    for path in loaded_files:
        lines.append(f'    "{path}"')
    lines.extend(
        [
            ")",
            f'set(HSS_CONFIG_COMPILE_DEFINITIONS "{all_definitions}")',
            f'set(HSS_CONFIG_FRAMEWORK_COMPILE_DEFINITIONS "{framework_definitions}")',
        ]
    )
    for key in sorted(values):
        value = values[key]
        if value.kind == "string":
            rendered = str(value.value).replace("\\", "\\\\").replace('"', '\\"')
        else:
            rendered = c_literal(value)
        lines.append(f'set(HSS_CONFIG_VALUE_{key} "{rendered}")')
    lines.append("")
    return "\n".join(lines)


def generated_meta(values: dict[str, ConfigValue], profiles: list[str], loaded_files: list[Path]) -> str:
    payload = {
        "profiles": profiles,
        "loaded_files": [str(path) for path in loaded_files],
        "values": {
            key: {
                "value": value.value,
                "kind": value.kind,
                "c_facing": is_c_facing(key),
                "macro": macro_name(key),
                "source": str(value.source.path),
                "line": value.source.line,
            }
            for key, value in sorted(values.items())
        },
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"
