# Generated by tools/board_sync; do not edit by hand.
# Source: stm32g071kb_temp_transmitter.ioc

set(BOARD_NAME stm32g071kb_temp_transmitter)
set(BOARD_CUBEMX_IOC ${CMAKE_CURRENT_LIST_DIR}/stm32g071kb_temp_transmitter.ioc)
set(BOARD_MCU_FAMILY stm32g0)
set(BOARD_MCU_DEVICE STM32G071KBTx)
set(BOARD_MCU_DEFINE STM32G071xx)
set(BOARD_CPU cortex-m0plus)

set(BOARD_CPU_FLAGS
        -mcpu=cortex-m0plus
        -mthumb
        -mfloat-abi=soft
)

set(BOARD_OPENOCD_INTERFACE interface/stlink.cfg)
set(BOARD_OPENOCD_TARGET target/stm32g0x.cfg)
set(BOARD_OPENOCD_TRANSPORT hla_swd)

set(BOARD_LINKER_SCRIPT ${CMAKE_CURRENT_LIST_DIR}/STM32G071XX_FLASH.ld)
set(BOARD_STARTUP_SOURCE ${CMAKE_CURRENT_LIST_DIR}/startup_stm32g071xx.s)
set(BOARD_GENERATED_DIR ${CMAKE_CURRENT_LIST_DIR}/generated)
set(BOARD_GENERATED_INCLUDE_DIR ${BOARD_GENERATED_DIR})

set(BOARD_CORE_INCLUDE_DIR ${CMAKE_CURRENT_LIST_DIR}/Core/Inc)
set(BOARD_CORE_SOURCES
        ${CMAKE_CURRENT_LIST_DIR}/Core/Src/gpio.c
        ${CMAKE_CURRENT_LIST_DIR}/Core/Src/main.c
        ${CMAKE_CURRENT_LIST_DIR}/Core/Src/spi.c
        ${CMAKE_CURRENT_LIST_DIR}/Core/Src/stm32g0xx_hal_msp.c
        ${CMAKE_CURRENT_LIST_DIR}/Core/Src/stm32g0xx_it.c
        ${CMAKE_CURRENT_LIST_DIR}/Core/Src/syscalls.c
        ${CMAKE_CURRENT_LIST_DIR}/Core/Src/sysmem.c
        ${CMAKE_CURRENT_LIST_DIR}/Core/Src/system_stm32g0xx.c
        ${CMAKE_CURRENT_LIST_DIR}/Core/Src/usart.c
)
set(BOARD_GLUE_SOURCES
        ${CMAKE_CURRENT_LIST_DIR}/generated/board_glue.c
)

set(BOARD_HAL_DRIVER_DIR ${CMAKE_CURRENT_LIST_DIR}/Drivers/STM32G0xx_HAL_Driver)
set(BOARD_CMSIS_CORE_DIR ${CMAKE_CURRENT_LIST_DIR}/Drivers/CMSIS/Include)
set(BOARD_CMSIS_DEVICE_DIR ${CMAKE_CURRENT_LIST_DIR}/Drivers/CMSIS/Device/ST/STM32G0xx/Include)

set(BOARD_CUBEMX_IPS
        NVIC
        RCC
        SPI1
        SYS
        USART1
)
