# Base config for the Blue Pill Modbus slave example.
HSS_ENABLE_FREEMODBUS=y
HSS_ENABLE_MAX31865=y
HSS_ENABLE_MODBUS_DEBUG=n
HSS_CONSOLE_STDIO_TIMEOUT_MS=1000

APP_DEVICE_NAME="blue-pill-modbus-slave"
APP_BOARD_REVISION="A"
APP_MODBUS_SLAVE_ID=1
APP_HOLDING_REGISTER_COUNT=8
