# Generated by tools/board_sync; do not edit by hand.
# Source: blue_pill_temp_transmitter.ioc

set(BOARD_NAME blue_pill_temp_transmitter)
set(BOARD_CUBEMX_IOC ${CMAKE_CURRENT_LIST_DIR}/blue_pill_temp_transmitter.ioc)
set(BOARD_MCU_FAMILY stm32f1)
set(BOARD_MCU_DEVICE STM32F103C8Tx)
set(BOARD_MCU_DEFINE STM32F103xB)
set(BOARD_CPU cortex-m3)

set(BOARD_CPU_FLAGS
        -mcpu=cortex-m3
        -mthumb
)

set(BOARD_OPENOCD_INTERFACE interface/stlink.cfg)
set(BOARD_OPENOCD_TARGET target/stm32f1x.cfg)

set(BOARD_LINKER_SCRIPT ${CMAKE_CURRENT_LIST_DIR}/STM32F103XX_FLASH.ld)
set(BOARD_STARTUP_SOURCE ${CMAKE_CURRENT_LIST_DIR}/startup_stm32f103xb.s)
set(BOARD_GENERATED_DIR ${CMAKE_CURRENT_LIST_DIR}/generated)
set(BOARD_GENERATED_INCLUDE_DIR ${BOARD_GENERATED_DIR})

set(BOARD_CORE_INCLUDE_DIR ${CMAKE_CURRENT_LIST_DIR}/Core/Inc)
set(BOARD_CORE_SOURCES
        ${CMAKE_CURRENT_LIST_DIR}/Core/Src/dma.c
        ${CMAKE_CURRENT_LIST_DIR}/Core/Src/gpio.c
        ${CMAKE_CURRENT_LIST_DIR}/Core/Src/main.c
        ${CMAKE_CURRENT_LIST_DIR}/Core/Src/spi.c
        ${CMAKE_CURRENT_LIST_DIR}/Core/Src/stm32f1xx_hal_msp.c
        ${CMAKE_CURRENT_LIST_DIR}/Core/Src/stm32f1xx_it.c
        ${CMAKE_CURRENT_LIST_DIR}/Core/Src/syscalls.c
        ${CMAKE_CURRENT_LIST_DIR}/Core/Src/sysmem.c
        ${CMAKE_CURRENT_LIST_DIR}/Core/Src/system_stm32f1xx.c
        ${CMAKE_CURRENT_LIST_DIR}/Core/Src/tim.c
        ${CMAKE_CURRENT_LIST_DIR}/Core/Src/usart.c
)
set(BOARD_GLUE_SOURCES
        ${CMAKE_CURRENT_LIST_DIR}/generated/board_glue.c
)

set(BOARD_HAL_DRIVER_DIR ${CMAKE_CURRENT_LIST_DIR}/Drivers/STM32F1xx_HAL_Driver)
set(BOARD_CMSIS_CORE_DIR ${CMAKE_CURRENT_LIST_DIR}/Drivers/CMSIS/Include)
set(BOARD_CMSIS_DEVICE_DIR ${CMAKE_CURRENT_LIST_DIR}/Drivers/CMSIS/Device/ST/STM32F1xx/Include)

set(BOARD_CUBEMX_IPS
        DMA
        NVIC
        RCC
        SPI1
        SYS
        TIM2
        USART1
)
